FROM golang:1.16-alpine3.13

# set argument vars in docker-run command
ARG SERVER_ADDRESS
ARG PSQL_SOURCE
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_DEFAULT_REGION

ENV SERVER_ADDRESS $SERVER_ADDRESS
ENV PSQL_SOURCE $PSQL_SOURCE
ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
ENV AWS_DEFAULT_REGION $AWS_DEFAULT_REGION

RUN apk add build-base
RUN mkdir /dist
ADD . /dist
WORKDIR /dist
RUN go build -o main cmd/main.go

EXPOSE 8080
CMD ["/dist/main", "-run"]

